name: Visit Website Every Hour

on:
  schedule:
    - cron: "0 * * * *"  # ⏰ Ejecuta cada hora en punto (UTC)
  workflow_dispatch:       # Permite ejecutarlo manualmente también

jobs:
  visit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libatk-bridge2.0-0 \
          libnss3 \
          libgbm1 \
          libasound2t64 \
          libxss1 \
          libxcomposite1 \
          libxdamage1 \
          libxrandr2 \
          libx11-xcb1 \
          libgdk-pixbuf2.0-0 \
          libnspr4 \
          fonts-liberation \
          xdg-utils \
          wget
      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Visit the website
        run: node visit.js

